// Code generated by MockGen. DO NOT EDIT.
// Source: hospital/src/internal/modules/domain/patient/service (interfaces: IPatientRepo)

// Package service is a generated GoMock package.
package service

import (
	context "context"
	dto "hospital/src/internal/modules/domain/patient/dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPatientRepo is a mock of IPatientRepo interface.
type MockIPatientRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIPatientRepoMockRecorder
}

// MockIPatientRepoMockRecorder is the mock recorder for MockIPatientRepo.
type MockIPatientRepoMockRecorder struct {
	mock *MockIPatientRepo
}

// NewMockIPatientRepo creates a new mock instance.
func NewMockIPatientRepo(ctrl *gomock.Controller) *MockIPatientRepo {
	mock := &MockIPatientRepo{ctrl: ctrl}
	mock.recorder = &MockIPatientRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPatientRepo) EXPECT() *MockIPatientRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPatientRepo) Create(arg0 context.Context, arg1 *dto.CreatePatient) (*dto.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*dto.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIPatientRepoMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPatientRepo)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockIPatientRepo) Delete(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIPatientRepoMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIPatientRepo)(nil).Delete), arg0, arg1)
}

// GetById mocks base method.
func (m *MockIPatientRepo) GetById(arg0 context.Context, arg1 int32) (*dto.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(*dto.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIPatientRepoMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIPatientRepo)(nil).GetById), arg0, arg1)
}

// List mocks base method.
func (m *MockIPatientRepo) List(arg0 context.Context) (dto.Patients, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].(dto.Patients)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIPatientRepoMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIPatientRepo)(nil).List), arg0)
}

// Update mocks base method.
func (m *MockIPatientRepo) Update(arg0 context.Context, arg1 int32, arg2 *dto.UpdatePatient) (*dto.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIPatientRepoMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIPatientRepo)(nil).Update), arg0, arg1, arg2)
}
