// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"hospital/internal/modules/db/ent/disease"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Disease is the model entity for the Disease schema.
type Disease struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Threat holds the value of the "threat" field.
	Threat string `json:"threat,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// DegreeOfDanger holds the value of the "degreeOfDanger" field.
	DegreeOfDanger int `json:"degreeOfDanger,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DiseaseQuery when eager-loading is set.
	Edges        DiseaseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DiseaseEdges holds the relations/edges for other nodes in the graph.
type DiseaseEdges struct {
	// Has holds the value of the has edge.
	Has []*Patient `json:"has,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HasOrErr returns the Has value or an error if the edge
// was not loaded in eager-loading.
func (e DiseaseEdges) HasOrErr() ([]*Patient, error) {
	if e.loadedTypes[0] {
		return e.Has, nil
	}
	return nil, &NotLoadedError{edge: "has"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Disease) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case disease.FieldID, disease.FieldDegreeOfDanger:
			values[i] = new(sql.NullInt64)
		case disease.FieldThreat, disease.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Disease fields.
func (d *Disease) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case disease.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = int(value.Int64)
		case disease.FieldThreat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field threat", values[i])
			} else if value.Valid {
				d.Threat = value.String
			}
		case disease.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				d.Name = value.String
			}
		case disease.FieldDegreeOfDanger:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field degreeOfDanger", values[i])
			} else if value.Valid {
				d.DegreeOfDanger = int(value.Int64)
			}
		default:
			d.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Disease.
// This includes values selected through modifiers, order, etc.
func (d *Disease) Value(name string) (ent.Value, error) {
	return d.selectValues.Get(name)
}

// QueryHas queries the "has" edge of the Disease entity.
func (d *Disease) QueryHas() *PatientQuery {
	return NewDiseaseClient(d.config).QueryHas(d)
}

// Update returns a builder for updating this Disease.
// Note that you need to call Disease.Unwrap() before calling this method if this Disease
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Disease) Update() *DiseaseUpdateOne {
	return NewDiseaseClient(d.config).UpdateOne(d)
}

// Unwrap unwraps the Disease entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Disease) Unwrap() *Disease {
	_tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Disease is not a transactional entity")
	}
	d.config.driver = _tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Disease) String() string {
	var builder strings.Builder
	builder.WriteString("Disease(")
	builder.WriteString(fmt.Sprintf("id=%v, ", d.ID))
	builder.WriteString("threat=")
	builder.WriteString(d.Threat)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(d.Name)
	builder.WriteString(", ")
	builder.WriteString("degreeOfDanger=")
	builder.WriteString(fmt.Sprintf("%v", d.DegreeOfDanger))
	builder.WriteByte(')')
	return builder.String()
}

// Diseases is a parsable slice of Disease.
type Diseases []*Disease
