// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hospital/internal/modules/db/ent/disease"
	"hospital/internal/modules/db/ent/patient"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DiseaseCreate is the builder for creating a Disease entity.
type DiseaseCreate struct {
	config
	mutation *DiseaseMutation
	hooks    []Hook
}

// SetThreat sets the "threat" field.
func (dc *DiseaseCreate) SetThreat(s string) *DiseaseCreate {
	dc.mutation.SetThreat(s)
	return dc
}

// SetName sets the "name" field.
func (dc *DiseaseCreate) SetName(s string) *DiseaseCreate {
	dc.mutation.SetName(s)
	return dc
}

// SetDegreeOfDanger sets the "degreeOfDanger" field.
func (dc *DiseaseCreate) SetDegreeOfDanger(i int) *DiseaseCreate {
	dc.mutation.SetDegreeOfDanger(i)
	return dc
}

// AddHaIDs adds the "has" edge to the Patient entity by IDs.
func (dc *DiseaseCreate) AddHaIDs(ids ...int) *DiseaseCreate {
	dc.mutation.AddHaIDs(ids...)
	return dc
}

// AddHas adds the "has" edges to the Patient entity.
func (dc *DiseaseCreate) AddHas(p ...*Patient) *DiseaseCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return dc.AddHaIDs(ids...)
}

// Mutation returns the DiseaseMutation object of the builder.
func (dc *DiseaseCreate) Mutation() *DiseaseMutation {
	return dc.mutation
}

// Save creates the Disease in the database.
func (dc *DiseaseCreate) Save(ctx context.Context) (*Disease, error) {
	return withHooks[*Disease, DiseaseMutation](ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DiseaseCreate) SaveX(ctx context.Context) *Disease {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DiseaseCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DiseaseCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DiseaseCreate) check() error {
	if _, ok := dc.mutation.Threat(); !ok {
		return &ValidationError{Name: "threat", err: errors.New(`ent: missing required field "Disease.threat"`)}
	}
	if _, ok := dc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Disease.name"`)}
	}
	if _, ok := dc.mutation.DegreeOfDanger(); !ok {
		return &ValidationError{Name: "degreeOfDanger", err: errors.New(`ent: missing required field "Disease.degreeOfDanger"`)}
	}
	return nil
}

func (dc *DiseaseCreate) sqlSave(ctx context.Context) (*Disease, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DiseaseCreate) createSpec() (*Disease, *sqlgraph.CreateSpec) {
	var (
		_node = &Disease{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(disease.Table, sqlgraph.NewFieldSpec(disease.FieldID, field.TypeInt))
	)
	if value, ok := dc.mutation.Threat(); ok {
		_spec.SetField(disease.FieldThreat, field.TypeString, value)
		_node.Threat = value
	}
	if value, ok := dc.mutation.Name(); ok {
		_spec.SetField(disease.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := dc.mutation.DegreeOfDanger(); ok {
		_spec.SetField(disease.FieldDegreeOfDanger, field.TypeInt, value)
		_node.DegreeOfDanger = value
	}
	if nodes := dc.mutation.HasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   disease.HasTable,
			Columns: []string{disease.HasColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DiseaseCreateBulk is the builder for creating many Disease entities in bulk.
type DiseaseCreateBulk struct {
	config
	builders []*DiseaseCreate
}

// Save creates the Disease entities in the database.
func (dcb *DiseaseCreateBulk) Save(ctx context.Context) ([]*Disease, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Disease, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiseaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DiseaseCreateBulk) SaveX(ctx context.Context) []*Disease {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DiseaseCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DiseaseCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}
