// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hospital/internal/modules/db/ent/doctor"
	"hospital/internal/modules/db/ent/patient"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DoctorCreate is the builder for creating a Doctor entity.
type DoctorCreate struct {
	config
	mutation *DoctorMutation
	hooks    []Hook
}

// SetTokenId sets the "tokenId" field.
func (dc *DoctorCreate) SetTokenId(s string) *DoctorCreate {
	dc.mutation.SetTokenId(s)
	return dc
}

// SetSurname sets the "surname" field.
func (dc *DoctorCreate) SetSurname(s string) *DoctorCreate {
	dc.mutation.SetSurname(s)
	return dc
}

// SetSpeciality sets the "speciality" field.
func (dc *DoctorCreate) SetSpeciality(s string) *DoctorCreate {
	dc.mutation.SetSpeciality(s)
	return dc
}

// SetRole sets the "role" field.
func (dc *DoctorCreate) SetRole(s string) *DoctorCreate {
	dc.mutation.SetRole(s)
	return dc
}

// AddTreatIDs adds the "treats" edge to the Patient entity by IDs.
func (dc *DoctorCreate) AddTreatIDs(ids ...int) *DoctorCreate {
	dc.mutation.AddTreatIDs(ids...)
	return dc
}

// AddTreats adds the "treats" edges to the Patient entity.
func (dc *DoctorCreate) AddTreats(p ...*Patient) *DoctorCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return dc.AddTreatIDs(ids...)
}

// Mutation returns the DoctorMutation object of the builder.
func (dc *DoctorCreate) Mutation() *DoctorMutation {
	return dc.mutation
}

// Save creates the Doctor in the database.
func (dc *DoctorCreate) Save(ctx context.Context) (*Doctor, error) {
	return withHooks[*Doctor, DoctorMutation](ctx, dc.sqlSave, dc.mutation, dc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DoctorCreate) SaveX(ctx context.Context) *Doctor {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dc *DoctorCreate) Exec(ctx context.Context) error {
	_, err := dc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dc *DoctorCreate) ExecX(ctx context.Context) {
	if err := dc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dc *DoctorCreate) check() error {
	if _, ok := dc.mutation.TokenId(); !ok {
		return &ValidationError{Name: "tokenId", err: errors.New(`ent: missing required field "Doctor.tokenId"`)}
	}
	if _, ok := dc.mutation.Surname(); !ok {
		return &ValidationError{Name: "surname", err: errors.New(`ent: missing required field "Doctor.surname"`)}
	}
	if _, ok := dc.mutation.Speciality(); !ok {
		return &ValidationError{Name: "speciality", err: errors.New(`ent: missing required field "Doctor.speciality"`)}
	}
	if _, ok := dc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Doctor.role"`)}
	}
	return nil
}

func (dc *DoctorCreate) sqlSave(ctx context.Context) (*Doctor, error) {
	if err := dc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	dc.mutation.id = &_node.ID
	dc.mutation.done = true
	return _node, nil
}

func (dc *DoctorCreate) createSpec() (*Doctor, *sqlgraph.CreateSpec) {
	var (
		_node = &Doctor{config: dc.config}
		_spec = sqlgraph.NewCreateSpec(doctor.Table, sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeInt))
	)
	if value, ok := dc.mutation.TokenId(); ok {
		_spec.SetField(doctor.FieldTokenId, field.TypeString, value)
		_node.TokenId = value
	}
	if value, ok := dc.mutation.Surname(); ok {
		_spec.SetField(doctor.FieldSurname, field.TypeString, value)
		_node.Surname = value
	}
	if value, ok := dc.mutation.Speciality(); ok {
		_spec.SetField(doctor.FieldSpeciality, field.TypeString, value)
		_node.Speciality = value
	}
	if value, ok := dc.mutation.Role(); ok {
		_spec.SetField(doctor.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if nodes := dc.mutation.TreatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   doctor.TreatsTable,
			Columns: doctor.TreatsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DoctorCreateBulk is the builder for creating many Doctor entities in bulk.
type DoctorCreateBulk struct {
	config
	builders []*DoctorCreate
}

// Save creates the Doctor entities in the database.
func (dcb *DoctorCreateBulk) Save(ctx context.Context) ([]*Doctor, error) {
	specs := make([]*sqlgraph.CreateSpec, len(dcb.builders))
	nodes := make([]*Doctor, len(dcb.builders))
	mutators := make([]Mutator, len(dcb.builders))
	for i := range dcb.builders {
		func(i int, root context.Context) {
			builder := dcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DoctorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcb *DoctorCreateBulk) SaveX(ctx context.Context) []*Doctor {
	v, err := dcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcb *DoctorCreateBulk) Exec(ctx context.Context) error {
	_, err := dcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcb *DoctorCreateBulk) ExecX(ctx context.Context) {
	if err := dcb.Exec(ctx); err != nil {
		panic(err)
	}
}
