// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"hospital/internal/modules/db/ent/doctor"
	"hospital/internal/modules/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DoctorDelete is the builder for deleting a Doctor entity.
type DoctorDelete struct {
	config
	hooks    []Hook
	mutation *DoctorMutation
}

// Where appends a list predicates to the DoctorDelete builder.
func (dd *DoctorDelete) Where(ps ...predicate.Doctor) *DoctorDelete {
	dd.mutation.Where(ps...)
	return dd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dd *DoctorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, DoctorMutation](ctx, dd.sqlExec, dd.mutation, dd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dd *DoctorDelete) ExecX(ctx context.Context) int {
	n, err := dd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dd *DoctorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(doctor.Table, sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeInt))
	if ps := dd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dd.mutation.done = true
	return affected, err
}

// DoctorDeleteOne is the builder for deleting a single Doctor entity.
type DoctorDeleteOne struct {
	dd *DoctorDelete
}

// Where appends a list predicates to the DoctorDelete builder.
func (ddo *DoctorDeleteOne) Where(ps ...predicate.Doctor) *DoctorDeleteOne {
	ddo.dd.mutation.Where(ps...)
	return ddo
}

// Exec executes the deletion query.
func (ddo *DoctorDeleteOne) Exec(ctx context.Context) error {
	n, err := ddo.dd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{doctor.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ddo *DoctorDeleteOne) ExecX(ctx context.Context) {
	if err := ddo.Exec(ctx); err != nil {
		panic(err)
	}
}
