// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hospital/internal/modules/db/ent/patient"
	"hospital/internal/modules/db/ent/room"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoomCreate is the builder for creating a Room entity.
type RoomCreate struct {
	config
	mutation *RoomMutation
	hooks    []Hook
}

// SetNumber sets the "number" field.
func (rc *RoomCreate) SetNumber(i int) *RoomCreate {
	rc.mutation.SetNumber(i)
	return rc
}

// SetFloor sets the "floor" field.
func (rc *RoomCreate) SetFloor(i int) *RoomCreate {
	rc.mutation.SetFloor(i)
	return rc
}

// SetNumberBeds sets the "numberBeds" field.
func (rc *RoomCreate) SetNumberBeds(i int) *RoomCreate {
	rc.mutation.SetNumberBeds(i)
	return rc
}

// SetNumberPatients sets the "numberPatients" field.
func (rc *RoomCreate) SetNumberPatients(i int) *RoomCreate {
	rc.mutation.SetNumberPatients(i)
	return rc
}

// SetTypeRoom sets the "typeRoom" field.
func (rc *RoomCreate) SetTypeRoom(s string) *RoomCreate {
	rc.mutation.SetTypeRoom(s)
	return rc
}

// AddContainIDs adds the "contains" edge to the Patient entity by IDs.
func (rc *RoomCreate) AddContainIDs(ids ...int) *RoomCreate {
	rc.mutation.AddContainIDs(ids...)
	return rc
}

// AddContains adds the "contains" edges to the Patient entity.
func (rc *RoomCreate) AddContains(p ...*Patient) *RoomCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return rc.AddContainIDs(ids...)
}

// Mutation returns the RoomMutation object of the builder.
func (rc *RoomCreate) Mutation() *RoomMutation {
	return rc.mutation
}

// Save creates the Room in the database.
func (rc *RoomCreate) Save(ctx context.Context) (*Room, error) {
	return withHooks[*Room, RoomMutation](ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RoomCreate) SaveX(ctx context.Context) *Room {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RoomCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RoomCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RoomCreate) check() error {
	if _, ok := rc.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "Room.number"`)}
	}
	if _, ok := rc.mutation.Floor(); !ok {
		return &ValidationError{Name: "floor", err: errors.New(`ent: missing required field "Room.floor"`)}
	}
	if _, ok := rc.mutation.NumberBeds(); !ok {
		return &ValidationError{Name: "numberBeds", err: errors.New(`ent: missing required field "Room.numberBeds"`)}
	}
	if _, ok := rc.mutation.NumberPatients(); !ok {
		return &ValidationError{Name: "numberPatients", err: errors.New(`ent: missing required field "Room.numberPatients"`)}
	}
	if _, ok := rc.mutation.TypeRoom(); !ok {
		return &ValidationError{Name: "typeRoom", err: errors.New(`ent: missing required field "Room.typeRoom"`)}
	}
	return nil
}

func (rc *RoomCreate) sqlSave(ctx context.Context) (*Room, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RoomCreate) createSpec() (*Room, *sqlgraph.CreateSpec) {
	var (
		_node = &Room{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(room.Table, sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt))
	)
	if value, ok := rc.mutation.Number(); ok {
		_spec.SetField(room.FieldNumber, field.TypeInt, value)
		_node.Number = value
	}
	if value, ok := rc.mutation.Floor(); ok {
		_spec.SetField(room.FieldFloor, field.TypeInt, value)
		_node.Floor = value
	}
	if value, ok := rc.mutation.NumberBeds(); ok {
		_spec.SetField(room.FieldNumberBeds, field.TypeInt, value)
		_node.NumberBeds = value
	}
	if value, ok := rc.mutation.NumberPatients(); ok {
		_spec.SetField(room.FieldNumberPatients, field.TypeInt, value)
		_node.NumberPatients = value
	}
	if value, ok := rc.mutation.TypeRoom(); ok {
		_spec.SetField(room.FieldTypeRoom, field.TypeString, value)
		_node.TypeRoom = value
	}
	if nodes := rc.mutation.ContainsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.ContainsTable,
			Columns: []string{room.ContainsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RoomCreateBulk is the builder for creating many Room entities in bulk.
type RoomCreateBulk struct {
	config
	builders []*RoomCreate
}

// Save creates the Room entities in the database.
func (rcb *RoomCreateBulk) Save(ctx context.Context) ([]*Room, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Room, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoomMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RoomCreateBulk) SaveX(ctx context.Context) []*Room {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RoomCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RoomCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
