// Code generated by MockGen. DO NOT EDIT.
// Source: hospital/src/internal/modules/domain/auth/service (interfaces: IUserRepo)

// Package service is a generated GoMock package.
package service

import (
	context "context"
	dto "hospital/src/internal/modules/domain/doctor/dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIUserRepo is a mock of IUserRepo interface.
type MockIUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIUserRepoMockRecorder
}

// MockIUserRepoMockRecorder is the mock recorder for MockIUserRepo.
type MockIUserRepoMockRecorder struct {
	mock *MockIUserRepo
}

// NewMockIUserRepo creates a new mock instance.
func NewMockIUserRepo(ctrl *gomock.Controller) *MockIUserRepo {
	mock := &MockIUserRepo{ctrl: ctrl}
	mock.recorder = &MockIUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserRepo) EXPECT() *MockIUserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIUserRepo) Create(arg0 context.Context, arg1 *dto.CreateDoctor) (*dto.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*dto.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIUserRepoMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUserRepo)(nil).Create), arg0, arg1)
}

// GetByTokenId mocks base method.
func (m *MockIUserRepo) GetByTokenId(arg0 context.Context, arg1 int32) (*dto.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenId", arg0, arg1)
	ret0, _ := ret[0].(*dto.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenId indicates an expected call of GetByTokenId.
func (mr *MockIUserRepoMockRecorder) GetByTokenId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenId", reflect.TypeOf((*MockIUserRepo)(nil).GetByTokenId), arg0, arg1)
}
