// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DoctorsColumns holds the columns for the "doctors" table.
	DoctorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_id", Type: field.TypeString, Unique: true},
		{Name: "surname", Type: field.TypeString},
		{Name: "speciality", Type: field.TypeString},
		{Name: "role", Type: field.TypeString},
	}
	// DoctorsTable holds the schema information for the "doctors" table.
	DoctorsTable = &schema.Table{
		Name:       "doctors",
		Columns:    DoctorsColumns,
		PrimaryKey: []*schema.Column{DoctorsColumns[0]},
	}
	// PatientsColumns holds the columns for the "patients" table.
	PatientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// PatientsTable holds the schema information for the "patients" table.
	PatientsTable = &schema.Table{
		Name:       "patients",
		Columns:    PatientsColumns,
		PrimaryKey: []*schema.Column{PatientsColumns[0]},
	}
	// DoctorPatientColumns holds the columns for the "doctor_patient" table.
	DoctorPatientColumns = []*schema.Column{
		{Name: "doctor_id", Type: field.TypeInt},
		{Name: "patient_id", Type: field.TypeInt},
	}
	// DoctorPatientTable holds the schema information for the "doctor_patient" table.
	DoctorPatientTable = &schema.Table{
		Name:       "doctor_patient",
		Columns:    DoctorPatientColumns,
		PrimaryKey: []*schema.Column{DoctorPatientColumns[0], DoctorPatientColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "doctor_patient_doctor_id",
				Columns:    []*schema.Column{DoctorPatientColumns[0]},
				RefColumns: []*schema.Column{DoctorsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "doctor_patient_patient_id",
				Columns:    []*schema.Column{DoctorPatientColumns[1]},
				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DoctorsTable,
		PatientsTable,
		DoctorPatientTable,
	}
)

func init() {
	DoctorPatientTable.ForeignKeys[0].RefTable = DoctorsTable
	DoctorPatientTable.ForeignKeys[1].RefTable = PatientsTable
}
